%insert_addon_code(SpinOnSpikySpriteHack)
%insert_addon_code(init_extra_sprites)
%insert_addon_code(custom_bubble)
%insert_addon_code(solid_sprite_fix)
%insert_addon_code(fix_tanooki_death)
%insert_addon_code(Paralyze)