%insert_addon_hack(SpinOnSpikySpriteHack)
%insert_addon_hack(init_extra_sprites)
%insert_addon_hack(custom_bubble)
%insert_addon_hack(solid_sprite_fix)
%insert_addon_hack(fix_tanooki_death)
%insert_addon_hack(Paralyze)